/*
 *  Unicode description, in German - Uebersetzung: GBV Hachmann 05.2011
 *
 *  You may defined your localized unicode character names for the diacritics bar here.
 *  You may define one description for each Code Point.
 *  THIS FILE MUST BE SAVED AS UTF8!!
 */

pref("winibw.diacritics.description.0", "Kyrillisches Härtezeichen");
pref("winibw.diacritics.description.1", "Subfield-Kennzeichen. Nicht eingeben!");
pref("winibw.diacritics.description.2", "Polnisches L groß");
pref("winibw.diacritics.description.3", "Skandinavisches O mit Strich groß");
pref("winibw.diacritics.description.4", "Serbokroatisches D groß");
pref("winibw.diacritics.description.5", "Thorn groß");
pref("winibw.diacritics.description.6", "Ligatur AE groß");
pref("winibw.diacritics.description.7", "Ligatur OE groß");
pref("winibw.diacritics.description.8", "Kyrillisches Weichheitszeichen");
pref("winibw.diacritics.description.9", "Zentrierter Punkt");
pref("winibw.diacritics.description.10", "Erniedrigungszeichen (Notenschrift)");
pref("winibw.diacritics.description.11", "Registriertes Warenzeichen");
pref("winibw.diacritics.description.12", "Plus-Minus");
pref("winibw.diacritics.description.13", "Vietnamesischer O-Haken groß");
pref("winibw.diacritics.description.14", "Vietnamesischer U-Haken groß");
pref("winibw.diacritics.description.15", "Hamzah");
pref("winibw.diacritics.description.16", "Angström A groß");
pref("winibw.diacritics.description.17", "Ain");
pref("winibw.diacritics.description.18", "Polnisches l klein");
pref("winibw.diacritics.description.19", "Skandinavisches o mit Strich klein");
pref("winibw.diacritics.description.20", "Serbokroatisches d klein");
pref("winibw.diacritics.description.21", "Thorn klein");
pref("winibw.diacritics.description.22", "Ligatur ae klein");
pref("winibw.diacritics.description.23", "Ligatur oe klein");
pref("winibw.diacritics.description.24", "Türkisches i ohne Punkt klein");
pref("winibw.diacritics.description.25", "Währungszeichen Pfund Sterling");
pref("winibw.diacritics.description.26", "eth klein");
pref("winibw.diacritics.description.27", "Alpha");
pref("winibw.diacritics.description.28", "Vietnamesischer o-Haken klein");
pref("winibw.diacritics.description.29", "Vietnamesischer u-Haken klein");
pref("winibw.diacritics.description.30", "Deutsches Eszett");
pref("winibw.diacritics.description.31", "Angström a klein");
pref("winibw.diacritics.description.32", "Ligatur IJ groß");
pref("winibw.diacritics.description.33", "A-Umlaut groß");
pref("winibw.diacritics.description.34", "O-Umlaut groß");
pref("winibw.diacritics.description.35", "U-Umlaut groß");
pref("winibw.diacritics.description.36", "Offenes O groß");
pref("winibw.diacritics.description.37", "Umgekehrtes E groß");
pref("winibw.diacritics.description.38", "ungleich");
pref("winibw.diacritics.description.39", "Pfeil nach rechts");
pref("winibw.diacritics.description.40", "Kleiner gleich");
pref("winibw.diacritics.description.41", "Unendlich");
pref("winibw.diacritics.description.42", "Integral");
pref("winibw.diacritics.description.43", "Multiplikationszeichen");
pref("winibw.diacritics.description.44", "Paragraphenzeichen");
pref("winibw.diacritics.description.45", "Quadratwurzel");
pref("winibw.diacritics.description.46", "Reaktion");
pref("winibw.diacritics.description.47", "Größer gleich");
pref("winibw.diacritics.description.48", "Ligatur ij klein");
pref("winibw.diacritics.description.49", "a-Umlaut klein");
pref("winibw.diacritics.description.50", "o-Umlaut klein");
pref("winibw.diacritics.description.51", "u-Umlaut klein");
pref("winibw.diacritics.description.52", "Offenes o klein");
pref("winibw.diacritics.description.53", "Umgekehrtes e klein");
pref("winibw.diacritics.description.54", "Öffnendes Fragezeichen");
pref("winibw.diacritics.description.55", "Öffnendes Ausrufungszeichen");
pref("winibw.diacritics.description.56", "Beta");
pref("winibw.diacritics.description.57", "Euro");
pref("winibw.diacritics.description.58", "Gamma");
pref("winibw.diacritics.description.59", "Pi");
pref("winibw.diacritics.description.60", "Vietnamesisches Hochtonzeichen");
pref("winibw.diacritics.description.61", "Gravis");
pref("winibw.diacritics.description.62", "Akut");
pref("winibw.diacritics.description.63", "Circumflex");
pref("winibw.diacritics.description.64", "Tilde");
pref("winibw.diacritics.description.65", "Balken übergesetzt (Macron)");
pref("winibw.diacritics.description.66", "Halbkreis übergesetzt");
pref("winibw.diacritics.description.67", "Punkt übergesetzt");
pref("winibw.diacritics.description.68", "Punkte für Umlaute");
pref("winibw.diacritics.description.69", "Hacek (Caron)");
pref("winibw.diacritics.description.70", "Gradzeichen / Ringel übergesetzt");
pref("winibw.diacritics.description.71", "Doppelbogen 1. Teil/links");
pref("winibw.diacritics.description.72", "Doppelbogen 2. Teil/rechts");
pref("winibw.diacritics.description.73", "Komma als Akzent oben");
pref("winibw.diacritics.description.74", "Doppelakut");
pref("winibw.diacritics.description.75", "Candrabindu");
pref("winibw.diacritics.description.76", "Cédille");
pref("winibw.diacritics.description.77", "Ogonek");
pref("winibw.diacritics.description.78", "Punkt untergesetzt");
pref("winibw.diacritics.description.79", "2 Punkte untergesetzt");
pref("winibw.diacritics.description.80", "Ringel (Kreis) untergesetzt");
pref("winibw.diacritics.description.81", "Doppelter Strich untergesetzt");
pref("winibw.diacritics.description.82", "Strich untergesetzt");
pref("winibw.diacritics.description.83", "Linker Haken (Sedila)");
pref("winibw.diacritics.description.84", "Cédille rude");
pref("winibw.diacritics.description.85", "Halbkreis untergesetzt");
pref("winibw.diacritics.description.86", "Doppeltilde 2. Teil/rechts");
pref("winibw.diacritics.description.87", "Doppeltilde 1. Teil/links");
pref("winibw.diacritics.description.88", "Komma rechts mittelhoch");
pref("winibw.diacritics.description.89", "Trema");
pref("winibw.diacritics.description.90", "Copyright");
pref("winibw.diacritics.description.91", "Phonografische Rechte");
pref("winibw.diacritics.description.92", "Tschechisches U mit Ringel übergesetzt");
pref("winibw.diacritics.description.93", "Tschechisches u mit Ringel übergesetzt");
